enable only ansible job + update playbook

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,103 +5,9 @@ on:
     branches: ["main"]
 
 jobs:
-  # Job 1: Run unit tests
-  UT:
-    runs-on: ubuntu-latest
-
-    steps:
-      # -------------------------------------------------
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      # -------------------------------------------------
-      - name: Build and start containers
-        run: docker compose -f docker-compose.test.yml up -d --build db python
-
-      # -------------------------------------------------
-      - name: Wait for DB readiness
-        run: |
-          for i in {1..10}; do
-            docker exec postgres16 pg_isready -U admin && break
-            echo "waiting for db..."
-            sleep 3
-          done
-
-      # -------------------------------------------------
-      - name: Run unit tests
-        run: docker exec python poetry run pytest -v
-
-      # -------------------------------------------------
-      - name: Tear down
-        if: always()
-        run: docker compose -f docker-compose.test.yml down -v
-
-  # Job 2: Provision Infrastructure with Terraform
-  terraform:
-    needs: UT
-    name: Provision Infrastructure for ${{ matrix.region }}
-    runs-on: ubuntu-latest
-
-    strategy:
-      matrix:
-        region: [us-east-1] # add or remove as needed, xpl: [us-east-1, eu-west-1, ap-southeast-1]
-      fail-fast: false # continue other regions even if one fails
-
-    defaults:
-      run:
-        working-directory: ./terraform
-
-    steps:
-      # -------------------------------------------------
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      # -------------------------------------------------
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-
-      # -------------------------------------------------
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ matrix.region }}
-
-      # -------------------------------------------------
-      - name: Terraform Init
-        run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} init
-
-      # -------------------------------------------------
-      - name: Terraform Validate
-        run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} validate
-
-      # -------------------------------------------------
-      - name: Terraform Plan
-        run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} plan -out=tfplan -var="aws_region=${{ matrix.region }}" -var-file=${GITHUB_WORKSPACE}/terraform/env/dev.tfvars
-
-      # -------------------------------------------------
-      - name: Terraform Apply
-        run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} apply -auto-approve tfplan
-
-      # -------------------------------------------------
-      - name: Extract EC2 Public IP
-        id: ec2_ip
-        run: |
-          IP=$(terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} output -raw instance_public_ip 2>/dev/null || true)
-          echo "instance_ip=$IP" >> "$GITHUB_OUTPUT"
-
-    outputs: # to use IP in next jobs
-      ec2_ip: ${{ steps.ec2_ip.outputs.instance_ip }}
-
-  # Job 3: Cloud environment configuration and application deployment with Ansible
-  # Ansible:
-  #   needs: terraform
-  #   name: Configure Cloud environment (AWS EC2 instance) and deploy application
+  # # Job 1: Run unit tests
+  # UT:
   #   runs-on: ubuntu-latest
-  #   defaults:
-  #     run:
-  #       working-directory: ./ansible #
 
   #   steps:
   #     # -------------------------------------------------
@@ -109,19 +15,114 @@ jobs:
   #       uses: actions/checkout@v4
 
   #     # -------------------------------------------------
-  #     - name: Set up Ansible
+  #     - name: Build and start containers
+  #       run: docker compose -f docker-compose.test.yml up -d --build db python
+
+  #     # -------------------------------------------------
+  #     - name: Wait for DB readiness
   #       run: |
-  #         sudo apt-get update
-  #         sudo apt-get install -y ansible sshpass
+  #         for i in {1..10}; do
+  #           docker exec postgres16 pg_isready -U admin && break
+  #           echo "waiting for db..."
+  #           sleep 3
+  #         done
 
   #     # -------------------------------------------------
-  #     - name: Write SSH key
-  #       run: echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/aws_key.pem && chmod 400 /tmp/aws_key.pem
+  #     - name: Run unit tests
+  #       run: docker exec python poetry run pytest -v
 
   #     # -------------------------------------------------
-  #     - name: Run Ansible
-  #       run: ansible-playbook -i "${{ needs.terraform.outputs.ec2_ip }}," -u ubuntu --private-key /tmp/aws_key.pem playbook.yml
+  #     - name: Tear down
+  #       if: always()
+  #       run: docker compose -f docker-compose.test.yml down -v
 
+  # # Job 2: Provision Infrastructure with Terraform
+  # terraform:
+  #   needs: UT
+  #   name: Provision Infrastructure for ${{ matrix.region }}
+  #   runs-on: ubuntu-latest
+
+  #   strategy:
+  #     matrix:
+  #       region: [us-east-1] # add or remove as needed, xpl: [us-east-1, eu-west-1, ap-southeast-1]
+  #     fail-fast: false # continue other regions even if one fails
+
+  #   defaults:
+  #     run:
+  #       working-directory: ./terraform
+
+  #   steps:
+  #     # -------------------------------------------------
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+
+  #     # -------------------------------------------------
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v3
+
+  #     # -------------------------------------------------
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ matrix.region }}
+
+  #     # -------------------------------------------------
+  #     - name: Terraform Init
+  #       run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} init
+
+  #     # -------------------------------------------------
+  #     - name: Terraform Validate
+  #       run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} validate
+
+  #     # -------------------------------------------------
+  #     - name: Terraform Plan
+  #       run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} plan -out=tfplan -var="aws_region=${{ matrix.region }}" -var-file=${GITHUB_WORKSPACE}/terraform/env/dev.tfvars
+
+  #     # -------------------------------------------------
+  #     - name: Terraform Apply
+  #       run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} apply -auto-approve tfplan
+
+  #     # -------------------------------------------------
+  #     - name: Extract EC2 Public IP
+  #       id: ec2_ip
+  #       run: |
+  #         IP=$(terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} output -raw instance_public_ip 2>/dev/null || true)
+  #         echo "instance_ip=$IP" >> "$GITHUB_OUTPUT"
+
+  #   outputs: # to use IP in next jobs
+  #     ec2_ip: ${{ steps.ec2_ip.outputs.instance_ip }}
+
+  # Job 3: Cloud environment configuration and application deployment with Ansible
+  Ansible:
+    needs: terraform
+    name: Configure Cloud environment (AWS EC2 instance) and deploy application
+    runs-on: ubuntu-latest
+    env:
+      ANSIBLE_HOST_KEY_CHECKING: "False"
+    defaults:
+      run:
+        working-directory: ./ansible #
+
+    steps:
+      # -------------------------------------------------
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      # -------------------------------------------------
+      - name: Set up Ansible
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y ansible sshpass
+
+      # -------------------------------------------------
+      - name: Write SSH key
+        run: echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/aws_key.pem && chmod 400 /tmp/aws_key.pem
+
+      # -------------------------------------------------
+      - name: Run Ansible
+        run: ansible-playbook -i "13.217.198.142," -u ubuntu --private-key /tmp/aws_key.pem playbook.yml
 
 # Job 2: Infrastructure provisioning via shell script
 # launch-ec2: # shell script version
@@ -149,7 +150,7 @@ jobs:
 #       run: |
 #         bash ec2-launch.sh
 
-# Job 3: Cloud deployment (if no ansible)
+# Job 4: Cloud deployment
 # deploy:
 #   needs: Ansible
 #   runs-on: ubuntu-latest
